export default {
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL_NAME: "LOGIN_FAIL_NAME",
    LOGIN_FAIL_PASS: "LOGIN_FAIL_PASS",
    LOGOUT: "LOGOUT",
    SUCCESS: "SUCCESS",
    INVALID_NAME: "INVALID_NAME",
    INVALID_PASS: "INVALID_PASS"
}
